project:
  type: website
  render:
    - "*.qmd"      # Renderiza todos os arquivos .qmd na raiz
    - "!posts/"
    - "!disciplinas/aed2/gaming"
    - "!blog.qmd"
  output-dir: docs
  
website:
  title: "REAComp"
  site-url: "https://brunofx-ufersa.github.io/reacomp/"
  favicon: img/logo.png
  google-analytics: "G-ECV5W1L7CB"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: disciplinas/aed2/academic/index.qmd
        text: Recursos
      - contribuicao.qmd
      #- href: blog.qmd
      #  text: Blog
      - about.qmd
      #- href: atividades.qmd
      #  text: Tarefas
  page-footer: 
    border: false
    background: light
    left: "" 
    center: 
      - text: Licença
      - text: CC BY-SA 4.0
        href: http://creativecommons.org/licenses/by-sa/4.0/
      - text: — Portal construído com 
      - text: "Quarto"
        href: https://quarto.org/
    right: "" 
  sidebar:
    - section: "Árvores"
      id: trees
      title: "Árvores"
      style: "docked"
      background: light
      contents:
        - disciplinas/aed2/academic/unidade1/1-arvores.qmd
        - disciplinas/aed2/academic/unidade1/2-arvoresbinarias.qmd
        - disciplinas/aed2/academic/unidade1/3-arvoresbinariasdebusca.qmd
        - disciplinas/aed2/academic/unidade1/4-arvoresavl.qmd
    - section: "Estruturas Genéricas"
      id: generics
      title: "Estruturas Genéricas"
      style: "docked"
      background: light
      contents:
        - disciplinas/aed2/academic/unidade2/1-ponteiros.qmd
        - disciplinas/aed2/academic/unidade2/2-callback.qmd
        - disciplinas/aed2/academic/unidade2/3-memoria.qmd
        - disciplinas/aed2/academic/unidade2/4-calculadora.qmd
        - disciplinas/aed2/academic/unidade2/5-lista.qmd
    - section: "Tabela de Dispersão"
      id: hash
      title: "Tabela de Dispersão"
      style: "docked"
      background: light
      contents:
        - disciplinas/aed2/academic/unidade2/6-introhash.qmd
        - disciplinas/aed2/academic/unidade2/7-funcaohash.qmd
        - disciplinas/aed2/academic/unidade2/8-colisoes.qmd
        - disciplinas/aed2/academic/unidade2/9-tabeladinamica.qmd
        - disciplinas/aed2/academic/unidade2/10-filtrobloom.qmd
        - disciplinas/aed2/academic/unidade2/11-exercicios.qmd
    - title: "How-To"
      contents:
        - howto.qmd
        # navigation items

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd

format:
  html:
    highlight-style: a11y
    theme:
      light: [litera, styles.scss]
      dark:  [darkly, styles-dark.scss]
    toc: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

  
execute:      # Freezing Computations
  freeze: auto

glossary:
  path: glossary.yml
  popup: hover
  show: true